Django-practice/CRUD/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')), # posts app의 urls.py 파일로 이관
    path("users/", include("users.urls"))
]

Django-practice/posts/urls.py
from django.urls import path
from . import views

app_name = "posts" # url name below를 이용하기 위해 필요

urlpatterns = [
    path('', views.post_list, name = "list"), # url의 name을 list로 설정
    path('<int:pk>/', views.post_detail, name="detail"), # 지정한 type의 variable을 view 함수로 전달
    path('create/', views.post_create, name="create"),
    path('<int:pk>/update/', views.post_update, name="update"),
    path('<int:pk>/delete/', views.post_delete, name="delete")
]

Django-practice/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('', views.main, name="main"),
    path('login/', views.LoginView.as_view(), name="login"),
    # as_view(): 진입 메소드
    # HTTP request의 종류 알아내어, 해당 이름을 갖는 메소드로 request 중계
    path('logout/', views.log_out, name="logout")
]

Django-practice/posts/models.py
from pyexpat import model
from django.db import models

class Post(models.Model): # Post라는 DB = class = table 생성 for data 객체화
    # table columns below
    title = models.CharField(verbose_name="제목", max_length=100) # verbose_name for human-readable column
    writer = models.CharField(verbose_name="글쓴이", max_length=50)
    content = models.TextField(verbose_name="내용")
    
    created_at = models.DateTimeField(auto_now_add=True) # When object is first created
    updated_at = models.DateTimeField(auto_now=True) # When object.save()
    # auto_now or auto_now_add to True => field to have editable=False and blank=True set
    
    def __str__(self): # instance가 문자열로 어떻게 표현될지, 필수 X
        return self.title

Django-practice/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    name = models.CharField(verbose_name="이름", max_length=4)

    GENDER_CHOICE = [("MALE", "남자"), ("FEMALE", "여자")]
    gender = models.CharField(max_length=6, choices=GENDER_CHOICE)
    age = models.PositiveIntegerField(verbose_name="나이", null=True)

Django-practice/posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post # Post의 schema가 담긴 form = Post object를 생성/수정할 수 있음
        fields = "__all__"

Django-practice/users/forms.py
from django import forms
from .models import User

class LoginForm(forms.Form):
    email = forms.EmailField() # Email input type
    password = forms.CharField(widget=forms.PasswordInput) # Password input type

    def clean(self): # Form.cleaned_data 정의, Form's vaildation
        email = self.cleaned_data.get("email") # cleaned_data = a dictionary which survived from field's clean()
        password = self.cleaned_data.get("password")

        try:
            user = User.objects.get(username=email) # username을 email로 갖고 있는 User
            if user.check_password(password):
                return self.cleaned_data
            else: # Wrong password
                raise forms.ValidationError("Wrong password!") # Form becomes invalid, li로 message 나타남
        except User.DoesNotExist:
            raise forms.ValidationError("No user!") # Form becomes invalid

Django-practice/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post # DB에 접근 가능해짐 ✔
from .forms import PostForm # Post object 만들 수 있는 form object

def post_list(request): # request object
    posts = Post.objects.all() # DB의 Post objects 가져옴
    ctx = {'posts':posts}
    return render(request, template_name="posts/list.html", context=ctx) # object 자체 말고 딕셔너리 형태로 전달
# Render = send http response

def post_detail(request, pk):
    post = Post.objects.get(id=pk) # id = Django가 automatically 생성한 object의 primary key
    # post = get_object_or_404(Post, id=pk) 도 가능
    ctx = {'post':post}
    return render(request, template_name="posts/detail.html", context=ctx)


# def post_create(request):
#     if request.method == 'POST':
#         post = Post() # Post object 생성 (DB 변경 X)
#         post.title = request.POST['title'] # 사용자가 submit한 정보로 object 완성
#         post.writer = request.POST['writer']
#         post.content = request.POST['content']
#         post.save() # DB에 등록 -> migrate 필요
#         return redirect("posts:list")
#     else: # Show empty form
#         return render(request, template_name="posts/create.html")

def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("posts:list")
    else:
        form = PostForm() # Empty form object
        ctx = {"form":form}
        return render(request, template_name="posts/create-form.html", context=ctx)

def post_update(request, pk):
    post = get_object_or_404(Post, id=pk) # id가 pk인 Post object
    if request.method == 'POST': # DB 변경
        form = PostForm(request.POST, instance = post)
        if form.is_valid():
            form.save() # Update the existing instance
        return redirect("posts:detail", pk)
    else: # 수정
        form = PostForm(instance = post) # Accept an existing instance
        ctx = {'form':form}
        return render(request, template_name="posts/create-form.html", context=ctx)

def post_delete(request, pk):
    post = get_object_or_404(Post, id=pk)
    post.delete()
    return redirect("posts:list")

Django-practice/users/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import LoginForm
from django.contrib.auth import authenticate, login, logout

def main(request):
    return render(request, "users/main.html")

class LoginView(View): # 함수로도 가능
    def get(self, request):
        form = LoginForm() # Empty form
        return render(request, "users/login.html", {"form":form}) # Shorthand

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid(): # 내부적으로 clean() 실행
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=email, password=password)
            if user is not None: # 회원
                login(request, user)
                return render(request, "users/success.html")
            # return render(request, "users/login.html", {"form":form})
        return render(request, "users/login.html", {"form":form}) # invalid, 정보 담겨있는 Form

def log_out(request):
    logout(request)
    return redirect("users:main")

Django-practice/posts/templates/posts/create-form.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>포스트 작성</title>
  </head>

  <body>
    <form action="" method="POST">
      {% csrf_token %}
      <!-- 외부 공격 막기 위해 -->
      <table>
        {{ form.as_table }}
        <!-- Form object를 table로 만들어 줌 -->
      </table>

      <input type="submit" value="저장하기" />
    </form>
  </body>
</html>

Django-practice/posts/templates/posts/create.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>포스트 작성</title>
  </head>

  <body>
    <form action="" method="post">
      {% csrf_token %}
      <div>
        <label for="title">제목</label><br />
        <input type="text" name="title" id="title" />
        <!-- name이 instance property와 일치하도록 -->
      </div>
      <div>
        <label for="writer">글쓴이</label><br />
        <input type="text" name="writer" id="writer" />
      </div>
      <div>
        <label for="content">내용</label><br />
        <textarea name="content" id="content" cols="30" rows="10"></textarea>
      </div>
      <input type="submit" value="글쓰기" />
    </form>
  </body>
</html>

Django-practice/posts/templates/posts/detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>포스트 상세 정보</title>
  </head>

  <body>
    <h1>{{ post.title }}</h1>
    <span> {{ post.writer }}</span>
    <p>{{ post.content | linebreaksbr }}</p>
    <!-- linebreaksbr = 줄바꿈 있는 부분에 <br /> 붙여줌 -->
    <p>{{ post.created_at }}</p>
    <p>{{ post.updated_at }}</p>
    <a href="{% url 'posts:list' %}">리스트로 돌아가기</a> <br />
    <a href="{% url 'posts:update' post.id%}">수정하기</a> <br />
    <!-- url에 post.id 전달 -> pk화 -->
    <a href="{% url 'posts:delete' post.id%}">삭제하기</a>
    <!-- app name:url name-->
  </body>
</html>

Django-practice/posts/templates/posts/list.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width" />
    <title>글 리스트</title>
  </head>
  <body>
    {%for post in posts%}
    <!-- posts는 ctx의 key -->
    <h2>제목 : {{post.title}}</h2>
    <br />
    <h4>글쓴이 : {{post.writer}}</h4>
    {%endfor%}
  </body>
</html>

Django-practice/users/templates/users/login.html
{% extends 'users/main.html' %} {% block content %}
<form method="POST" action="">
  {% csrf_token %} {{form}}
  <button>Login</button>
</form>
{% endblock content %}

Django-practice/users/templates/users/main.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    {% if user.is_authenticated %}
    <li><a href="{% url 'users:logout' %}">Logout</a></li>
    {% else %}
    <li><a href="{% url 'users:login' %}">Login</a></li>
    {% endif %} {% block content %} {% endblock content %}
  </body>
</html>

Django-practice/users/templates/users/success.html
{% extends 'users/main.html' %} {% block content %} success! {%endblock %}